// ui/apps/public/app/pages/privacy.vue
<script setup lang="ts">
import { usePublicSeo } from "~/composables/usePublicSeo";

usePublicSeo({
  title: "Privacy Policy · Infinite Ocean",
  path: "/privacy",
  description: "How Infinite Ocean collects, uses, shares, protects and deletes personal information across its websites and services."
});
</script>

<template>
  <article class="legal-copy section-frame">
    <p class="eyebrow">Privacy Policy · Version 1.0 · Effective September 1, 2026</p>
    <h1>Privacy, in plain language.</h1>
    <p class="lede">We collect the information needed to run and secure Infinite Ocean services, including Spyglass. We do not sell personal information, use it for cross-context behavioral advertising, or share SMS consent for marketing.</p>

    <h2>Who this policy covers</h2>
    <p>This Privacy Policy applies to Infinite Ocean, LLC websites, applications and services that link to it, including infiniteocean.net, its subdomains and Spyglass (together, the “Services”). Infinite Ocean, LLC, a North Carolina limited liability company, is responsible for the personal information described here. Contact us at <a href="mailto:privacy@infiniteocean.net">privacy@infiniteocean.net</a>.</p>
    <p>When a business customer puts information about its employees, customers or other people into Spyglass, that customer controls why the information is used and Infinite Ocean generally processes it for the customer. Requests about that Customer Content should normally be directed to the customer that provided it. We remain responsible for account, billing, security, support and website information we control directly.</p>

    <h2>Information we collect</h2>
    <ul>
      <li><strong>Account and contact information:</strong> name, email address, business and team details, role, preferences and communications with us.</li>
      <li><strong>Authentication and security information:</strong> password verifiers, passkey public credentials, recovery and multi-factor status, phone number when you choose SMS authentication, Google sign-in identifiers, login events, IP address, device and browser information, and security audit records.</li>
      <li><strong>Customer Content:</strong> work, schedules, documents, answers, business records, agent instructions, prompts, tool results, integrations and other information an authorized user chooses to put into the Services.</li>
      <li><strong>Usage and diagnostics:</strong> feature use, service requests, timestamps, error and performance records, and necessary server logs.</li>
      <li><strong>Billing and commercial information:</strong> plan, subscription, invoice and payment status, Stripe customer references, purchases, tax status, affiliate code and commission records. Stripe receives payment-card details directly; we do not store full card numbers.</li>
      <li><strong>Support information:</strong> tickets, messages and the reason, duration and audit history for any authorized support inspection. Support inspection is time-limited and visibly recorded; staff do not silently become the customer.</li>
      <li><strong>Public-site consent and analytics:</strong> the choices saved for a browser and, only after consent, limited first-party events about the landing page, checkout handoff and onboarding journey.</li>
    </ul>
    <p>We receive information from you and your team, your browser or device, integrations you authorize, identity and communications providers, payment providers, and sources you deliberately ask the Services to retrieve.</p>

    <h2>How we use information</h2>
    <p>We use personal information to provide and secure the Services; create and administer accounts and teams; deliver authentication codes and service messages; process subscriptions, taxes and affiliate credits; run requested integrations and AI features; provide support; detect abuse and reliability problems; maintain audit evidence; meet legal obligations; and improve the Services.</p>
    <p>For people in the European Economic Area, United Kingdom or similar jurisdictions, our legal bases are performance of a contract, compliance with law, consent where we ask for it, and our legitimate interests in securing, supporting and improving a business service. You may withdraw consent at any time without affecting earlier lawful processing.</p>

    <h2>AI features</h2>
    <p>When an authorized user asks an AI feature to work with Customer Content, the relevant instructions and content may be sent to the model provider selected by the service configuration. We use that information to produce the requested result, enforce limits, meter AI Token usage and investigate failures. Model and provider choices may change as service configurations evolve. Do not submit information you are not authorized to use. Important legal, financial, employment, safety or regulatory decisions require qualified human review.</p>

    <h2>Analytics and storage choices</h2>
    <p>Necessary cookies and similar storage keep the Services secure, remember privacy choices and make signup and checkout work. Optional public-site analytics stays off until you accept it. Marketing tracking is not currently used.</p>
    <p>Public analytics events do not contain your name, email, user or team ID, payment details, prompts, answers, documents, evidence, task content, full URLs, query strings or referring pages. You may accept or reject optional analytics without changing your access, and change your choice here or inside the application.</p>

    <h2>How we disclose information</h2>
    <p>We disclose information only as needed to provide the Services: to hosting and infrastructure providers; Stripe for payments and taxes; identity providers such as Google when you choose them; communications and telecommunications providers for email or SMS; model providers for requested AI work; integration providers you authorize; professional advisers; and authorities when lawfully required. We may also disclose information in a merger, financing, reorganization or sale, subject to appropriate confidentiality and notice protections.</p>
    <p>We do not sell personal information. We do not share personal information for cross-context behavioral advertising or disclose it to third parties or affiliates for their own promotional or marketing purposes.</p>

    <h2>SMS and mobile information</h2>
    <p><strong>Your mobile information will not be sold or shared with third parties or affiliates for promotional or marketing purposes.</strong> Text messaging originator opt-in data and consent will not be shared with any third parties for purposes unrelated to providing the SMS service.</p>
    <p>We may share your phone number, SMS opt-in or consent status with telecommunications carriers, messaging platforms and vendors that help us deliver and secure requested text messages. They may use it only to provide those messaging services, prevent abuse, comply with carrier rules or satisfy law.</p>

    <h2>Retention and deletion</h2>
    <p>We keep information only as long as reasonably needed for the purposes above. Raw public-site analytics events are kept for up to 395 days. Browser consent history remains available so you can inspect your choices and may be erased sooner below.</p>
    <p>After an Account is closed, ordinary Customer Content enters a 30-day recovery period and is then scheduled for deletion. Limited billing, tax, affiliate, security, fraud-prevention, consent and audit records may be retained longer when required by law or reasonably necessary to establish, exercise or defend legal claims. Affiliate financial and audit records may be retained for seven years after the later of closure or final relevant activity. Backups expire on their normal protected schedule and are not restored to ordinary use except for disaster recovery.</p>

    <h2>Security</h2>
    <p>We use administrative, technical and organizational safeguards designed for the nature of the information, including encryption in transit, access controls, strong authentication, least-privilege service roles and audit trails. No service can guarantee absolute security. Please contact <a href="mailto:security@infiniteocean.net">security@infiniteocean.net</a> if you believe an account or the Services are at risk.</p>

    <h2>Your privacy rights</h2>
    <p>Depending on where you live, you may have rights to know, access, correct, export or delete personal information; restrict or object to processing; withdraw consent; and appeal or complain to a privacy regulator. We do not discriminate against anyone for exercising a privacy right.</p>
    <p>California residents may request the categories and specific pieces of personal information we hold, correction, deletion and information about disclosures. We have not sold or shared personal information as those terms are defined by the California Consumer Privacy Act during the preceding 12 months. We use sensitive personal information only for permitted purposes such as authentication, security, payments and providing requested services, not to infer personal characteristics.</p>
    <p>Submit an available request from the Privacy area inside Spyglass or email <a href="mailto:privacy@infiniteocean.net">privacy@infiniteocean.net</a>. We may verify your identity and authority before acting. An authorized agent may submit a request where applicable. If Customer Content is controlled by one of our business customers, we may direct the request to that customer.</p>

    <PublicConsentHistory />

    <h2>International processing</h2>
    <p>Infinite Ocean is based in the United States, and information may be processed in the United States and other countries where our providers operate. Where applicable law requires a transfer safeguard, we use an approved mechanism such as standard contractual clauses or another lawful basis. Contact us to request information about the safeguard applicable to your data.</p>

    <h2>Children</h2>
    <p>The Services are for businesses and are not directed to children under 18. We do not knowingly collect personal information from children. Contact us if you believe a child provided information to the Services.</p>

    <h2>Changes and contact</h2>
    <p>We may update this policy as the Services or law changes. We will post the effective date and provide additional notice when a material change requires it. Questions and privacy requests may be sent to <a href="mailto:privacy@infiniteocean.net">privacy@infiniteocean.net</a>. Support questions may be sent to <a href="mailto:support@infiniteocean.net">support@infiniteocean.net</a>.</p>
  </article>
</template>

// website/app/privacy/page.tsx
import type { Metadata } from "next";
import { MarketingPage, PageIntro } from "../_components/site-shell";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return <MarketingPage>
    <PageIntro eyebrow="Privacy Policy · Version 1.0 · Effective September 1, 2026" title="Privacy, in plain language." body="We collect the information needed to run and secure Infinite Ocean services. We do not sell personal information, use it for cross-context behavioral advertising, or share SMS consent for marketing." />
    <article className="prose">
      <h2>Who this policy covers</h2>
      <p>This policy applies to Infinite Ocean, LLC websites, applications and services that link to it, including infiniteocean.net, its subdomains and Spyglass. Contact the North Carolina company responsible for this information at <a href="mailto:privacy@infiniteocean.net">privacy@infiniteocean.net</a>.</p>
      <p>For business Customer Content, the customer normally determines why information is processed and Infinite Ocean provides the service on its behalf. We directly control account, billing, security, support and website information.</p>
      <h2>Information and uses</h2>
      <p>We collect account and contact details; authentication, phone and security records; Customer Content deliberately submitted to a service; usage and diagnostic records; Stripe-linked billing and affiliate records; support communications; and optional first-party analytics after consent. We use it to provide, secure, bill, support and improve the services, run requested integrations and AI features, prevent abuse, and meet legal obligations.</p>
      <h2>Analytics and AI</h2>
      <p>Optional public analytics stays off until accepted and excludes names, emails, user or team IDs, payment details, prompts, answers, documents, task content, full URLs, query strings and referring pages. Requested AI work may send the relevant instructions and Customer Content to the configured model provider to produce results, enforce limits and meter usage.</p>
      <h2>Disclosure and mobile information</h2>
      <p>We use providers for hosting, Stripe payments and taxes, identity, email, telecommunications, AI models and integrations selected by the customer. We do not sell personal information or share it for cross-context behavioral advertising.</p>
      <p><strong>Your mobile information will not be sold or shared with third parties or affiliates for promotional or marketing purposes.</strong> SMS opt-in data and consent are disclosed only to carriers, messaging platforms and providers that help deliver and secure the requested text-message service, or as law requires.</p>
      <h2>Retention</h2>
      <p>Raw public analytics is kept for up to 395 days. After Account closure, ordinary Customer Content enters a 30-day recovery period and is then scheduled for deletion. Limited billing, tax, affiliate, security, consent and audit records may remain longer when required; Affiliate financial records may be kept for seven years after final relevant activity.</p>
      <h2>Your rights</h2>
      <p>Depending on location, you may have rights to access, know, correct, export, delete or restrict personal information, object to processing, withdraw consent and complain to a regulator. We do not discriminate for exercising a right. We have not sold or shared personal information as defined by the California Consumer Privacy Act in the preceding 12 months and do not use sensitive information to infer characteristics.</p>
      <h2>International processing, security and children</h2>
      <p>Information may be processed in the United States and other provider locations using a lawful transfer safeguard where required. We use access controls, encryption in transit, strong authentication, least-privilege roles and audit trails, but no service can promise absolute security. The services are for businesses and not directed to children under 18.</p>
      <h2>Contact and changes</h2>
      <p>Submit a request through an available Spyglass privacy control or email <a href="mailto:privacy@infiniteocean.net">privacy@infiniteocean.net</a>. We may verify identity and authority. Material updates will be posted with a new effective date and additional notice where required.</p>
    </article>
  </MarketingPage>;
}
